name: Python CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      name: Checkout repository 
      uses: actions/checkout@v4
      
      name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: 3.8
    
      name: Run tests for suma.py
      run: python -m unittest test_suma.py

      name: Run tests for resta.py
      run: python -m unittest test_resta.py

      name: Run tests for multiplicacion.py
      run: python -m unittest test_multiplicacion.py

      name: Run tests for division.py
      run: python -m unittest test_division.py
